/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	securityprobedatadoghqcomv1 "github.com/Gui774ume/network-security-probe/pkg/k8s/apis/securityprobe.datadoghq.com/v1"
	versioned "github.com/Gui774ume/network-security-probe/pkg/k8s/client/clientset/versioned"
	internalinterfaces "github.com/Gui774ume/network-security-probe/pkg/k8s/client/informers/externalversions/internalinterfaces"
	v1 "github.com/Gui774ume/network-security-probe/pkg/k8s/client/listers/securityprobe.datadoghq.com/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SecurityProfileInformer provides access to a shared informer and lister for
// SecurityProfiles.
type SecurityProfileInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.SecurityProfileLister
}

type securityProfileInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSecurityProfileInformer constructs a new informer for SecurityProfile type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSecurityProfileInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSecurityProfileInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSecurityProfileInformer constructs a new informer for SecurityProfile type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSecurityProfileInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecurityprobeV1().SecurityProfiles(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecurityprobeV1().SecurityProfiles(namespace).Watch(options)
			},
		},
		&securityprobedatadoghqcomv1.SecurityProfile{},
		resyncPeriod,
		indexers,
	)
}

func (f *securityProfileInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSecurityProfileInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *securityProfileInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&securityprobedatadoghqcomv1.SecurityProfile{}, f.defaultInformer)
}

func (f *securityProfileInformer) Lister() v1.SecurityProfileLister {
	return v1.NewSecurityProfileLister(f.Informer().GetIndexer())
}
