/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	securityprobedatadoghqcomv1 "github.com/Gui774ume/network-security-probe/pkg/k8s/apis/securityprobe.datadoghq.com/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSecurityProfiles implements SecurityProfileInterface
type FakeSecurityProfiles struct {
	Fake *FakeSecurityprobeV1
	ns   string
}

var securityprofilesResource = schema.GroupVersionResource{Group: "securityprobe.datadoghq.com", Version: "v1", Resource: "securityprofiles"}

var securityprofilesKind = schema.GroupVersionKind{Group: "securityprobe.datadoghq.com", Version: "v1", Kind: "SecurityProfile"}

// Get takes name of the securityProfile, and returns the corresponding securityProfile object, and an error if there is any.
func (c *FakeSecurityProfiles) Get(name string, options v1.GetOptions) (result *securityprobedatadoghqcomv1.SecurityProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(securityprofilesResource, c.ns, name), &securityprobedatadoghqcomv1.SecurityProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*securityprobedatadoghqcomv1.SecurityProfile), err
}

// List takes label and field selectors, and returns the list of SecurityProfiles that match those selectors.
func (c *FakeSecurityProfiles) List(opts v1.ListOptions) (result *securityprobedatadoghqcomv1.SecurityProfileList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(securityprofilesResource, securityprofilesKind, c.ns, opts), &securityprobedatadoghqcomv1.SecurityProfileList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &securityprobedatadoghqcomv1.SecurityProfileList{ListMeta: obj.(*securityprobedatadoghqcomv1.SecurityProfileList).ListMeta}
	for _, item := range obj.(*securityprobedatadoghqcomv1.SecurityProfileList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested securityProfiles.
func (c *FakeSecurityProfiles) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(securityprofilesResource, c.ns, opts))

}

// Create takes the representation of a securityProfile and creates it.  Returns the server's representation of the securityProfile, and an error, if there is any.
func (c *FakeSecurityProfiles) Create(securityProfile *securityprobedatadoghqcomv1.SecurityProfile) (result *securityprobedatadoghqcomv1.SecurityProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(securityprofilesResource, c.ns, securityProfile), &securityprobedatadoghqcomv1.SecurityProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*securityprobedatadoghqcomv1.SecurityProfile), err
}

// Update takes the representation of a securityProfile and updates it. Returns the server's representation of the securityProfile, and an error, if there is any.
func (c *FakeSecurityProfiles) Update(securityProfile *securityprobedatadoghqcomv1.SecurityProfile) (result *securityprobedatadoghqcomv1.SecurityProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(securityprofilesResource, c.ns, securityProfile), &securityprobedatadoghqcomv1.SecurityProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*securityprobedatadoghqcomv1.SecurityProfile), err
}

// Delete takes name of the securityProfile and deletes it. Returns an error if one occurs.
func (c *FakeSecurityProfiles) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(securityprofilesResource, c.ns, name), &securityprobedatadoghqcomv1.SecurityProfile{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSecurityProfiles) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(securityprofilesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &securityprobedatadoghqcomv1.SecurityProfileList{})
	return err
}

// Patch applies the patch and returns the patched securityProfile.
func (c *FakeSecurityProfiles) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *securityprobedatadoghqcomv1.SecurityProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(securityprofilesResource, c.ns, name, pt, data, subresources...), &securityprobedatadoghqcomv1.SecurityProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*securityprobedatadoghqcomv1.SecurityProfile), err
}
